export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#141414", fontFamily: "sans-serif", color: "white" }}>{children}</body>
    </html>
  );
}
